[project]
name = "factoriollm"
version = "0.1.0"
description = "LLM based text to blueprint project for Factorio"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "factorio-draftsman>=3.3.1",
    "google-genai>=2.20.0",
    "httpx[socks]>=0.28.1",
    "python-dotenv>=1.2.3",
    "tenacity>=9.1.2",
    "tqdm>=4.67.1",
    "accelerate>=0.21.0",
    "bitsandbytes>=0.41.0",
    "datasets>=2.16.0",
    "peft>=0.11.1",
    "torch==2.6.0",
    "torchao==0.13.0",
    "torchaudio==2.6.0",
    "torchvision==0.21.0",
    "transformers>=4.40.0",
    "triton-windows",
    "trl>=0.9.0",
    "unsloth",
    "unsloth-zoo>=2026.10.1",
]

[project.scripts]
factoriollm = "factoriollm:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
index = [
  { name = "pytorch-cu124", url = "https://download.pytorch.org/whl/cu124", explicit = true }
]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
torchaudio = { index = "pytorch-cu124" }
unsloth = { git = "https://github.com/unslothai/unsloth.git" }
