from draftsman.blueprintable import Blueprint
from draftsman.constants import Direction
from draftsman.entity import Furnace, Inserter, TransportBelt

# Create a new blueprint
bp = Blueprint()
bp.label = "My First Auto-Smelter" # Blueprint label in game
bp.description = "Generated by Python"

furnaces_count = 5
two_rows = True  # Set to True for two rows of furnaces, False for one row
direction = Direction.EAST  # Direction for the furnaces (EAST means they face right)

for i in range(furnaces_count):
    # 1. Create a furnace (shift each subsequent one 2 tiles to the right)
    furnace = Furnace("stone-furnace", tile_position=(i * 2, 0))
    bp.entities.append(furnace)
    
    # 2. Create a conveyor belt in front of the furnace
    belt = TransportBelt("transport-belt", tile_position=(i * 2, -2), direction=direction) # Input belt in front of the furnace
    bp.entities.append(belt)
    belt = TransportBelt("transport-belt", tile_position=(i * 2, 3), direction=direction) # Output belt behind the furnace
    bp.entities.append(belt)
    
    # To make the conveyor belt continuous, add another segment between furnaces
    belt_gap = TransportBelt("transport-belt", tile_position=(i * 2 + 1, -2), direction=direction)
    bp.entities.append(belt_gap)
    belt_gap = TransportBelt("transport-belt", tile_position=(i * 2 + 1, 3), direction=direction)
    bp.entities.append(belt_gap)
    
    # 3. Create an inserter that takes items from the conveyor and puts them in the furnace
    # Direction NORTH means it "looks" down (takes from above, puts down)
    inserter = Inserter("inserter", tile_position=(i * 2, -1), direction=direction.previous())  # Inserter faces the furnace
    bp.entities.append(inserter)
    inserter = Inserter("inserter", tile_position=(i * 2, 2), direction=direction.previous())   # Output inserter (takes from furnace, puts on belt)
    bp.entities.append(inserter)

    if two_rows:
        # Create a second row of furnaces below the first row
        furnace2 = Furnace("stone-furnace", tile_position=(i * 2, 5))
        bp.entities.append(furnace2)
        
        # Create conveyor belts for the second row
        belt2 = TransportBelt("transport-belt", tile_position=(i * 2, 8), direction=direction) # Input belt in front of the second furnace
        bp.entities.append(belt2)
        
        # To make the conveyor belt continuous for the second row, add another segment between furnaces
        belt_gap2 = TransportBelt("transport-belt", tile_position=(i * 2 + 1, 8), direction=direction)
        bp.entities.append(belt_gap2)
        
        # Create inserters for the second row
        inserter2 = Inserter("inserter", tile_position=(i * 2, 4), direction=direction.next())  # Inserter faces the second furnace
        bp.entities.append(inserter2)
        inserter2 = Inserter("inserter", tile_position=(i * 2, 7), direction=direction.next())   # Output inserter (takes from second furnace, puts on belt)
        bp.entities.append(inserter2)

# Generate the final string for the game
print("\n--- COPY THE STRING BELOW ---")
print(bp.to_string())
print("----------------------------\n")